const categories=['Entreprise','Fiscalité','Administratif','Travail','Immobilier','Famille'];
const shelves=[
 ['Créer son activité','Entreprise','Pour passer de l’idée aux premières démarches.','navy'],
 ['Comprendre ses impôts','Fiscalité','Les notions utiles expliquées sans jargon.','blue'],
 ['Premières démarches','Administratif','Les formalités essentielles au même endroit.','sand'],
 ['Organiser son administratif','Organisation','Une méthode simple pour ne plus subir les papiers.','green']
];
export default function Home(){return <main>
<section className="editorialHero"><div className="heroWords"><span className="serLabel">SER GUIDES · LA BIBLIOTHÈQUE PRATIQUE</span><h1>Des repères clairs.<br/><em>Des décisions plus sereines.</em></h1><p>Des guides numériques conçus comme de vrais compagnons de route : comprendre, vérifier, agir — sans se perdre dans le jargon.</p><div className="heroActions"><a className="serButton" href="/guides/micro-entreprise-2026">Découvrir le Guide 01 <span>→</span></a><a className="quietLink" href="#bibliotheque">Explorer la bibliothèque</a></div><div className="heroProof"><span>Guides pratiques</span><span>Sources identifiables</span><span>Accès après achat</span></div></div><div className="heroVisual"><img src="/ser-micro-entreprise-hero.svg" alt="Univers éditorial SER Guides Micro-entreprise 2026"/><div className="visualCaption"><b>Micro-entreprise 2026</b><span>Guide 01 · Administratif & fiscal</span></div></div></section>
<section className="themeRail"><div><b>Explorer par thème</b>{categories.map(x=><a href="/guides" key={x}>{x}</a>)}</div></section>
<section className="spotlight"><div className="spotlightMedia"><img src="/ser-micro-entreprise-hero.svg" alt="Guide Micro-entreprise 2026"/></div><div className="spotlightCopy"><span className="serLabel">À LA UNE · GUIDE 01</span><h2>Micro-entreprise 2026</h2><p className="bigLead">Le guide interactif pour éviter les erreurs avant de commencer.</p><div className="benefits"><div><b>01</b><span><strong>Diagnostic rapide</strong><small>Situez votre projet et les démarches qui vous concernent.</small></span></div><div><b>02</b><span><strong>Aides & optimisation</strong><small>Identifiez les dispositifs et points de vigilance utiles.</small></span></div><div><b>03</b><span><strong>Déclarations simplifiées</strong><small>Avancez avec une feuille de route plus lisible.</small></span></div></div><div className="priceLine"><div><small>Guide numérique</small><strong>12,99 €</strong></div><a className="serButton" href="/guides/micro-entreprise-2026">Voir le guide →</a></div></div></section>
<section className="manifesto"><div className="manifestoQuote"><span>LE RÉFLEXE SER</span><h2>Avant d’agir,<br/><em>vérifiez toujours.</em></h2><p>Une information virale ne remplace jamais une source officielle. SER Guides transforme les sujets compliqués en parcours lisibles et actionnables.</p></div><div className="sourceCards"><div><span>01</span><b>Sources officielles</b><p>Les organismes et références utiles sont remis au centre du parcours.</p></div><div><span>02</span><b>Contexte</b><p>Une règle n’a de sens qu’avec sa situation, sa date et ses conditions.</p></div><div><span>03</span><b>Passage à l’action</b><p>Des étapes, checklists et repères pour savoir quoi faire ensuite.</p></div></div></section>
<section className="librarySection" id="bibliotheque"><div className="sectionHeading"><div><span className="serLabel">LA COLLECTION SER</span><h2>Une bibliothèque pour la vraie vie.</h2><p>Chaque sujet possède son propre univers visuel, tout en gardant la signature SER Guides.</p></div><a className="quietLink" href="/guides">Voir tous les guides →</a></div><div className="bookGrid"><a className="bookItem" href="/guides/micro-entreprise-2026"><div className="realCover"><span>SER · GUIDE 01</span><div><small>Entreprise</small><h3>Micro-<br/>entreprise</h3><strong>2026</strong></div><p>Comprendre · vérifier · avancer</p></div><div className="bookInfo"><span>Administratif & fiscal</span><h3>Micro-entreprise 2026</h3><p>Démarrer et gérer avec une feuille de route claire.</p><b>12,99 €</b></div></a>{shelves.map(([title,cat,desc,tone])=><div className="bookItem coming" key={title}><div className={'realCover '+tone}><span>SER · PROCHAINE PARUTION</span><div><small>{cat}</small><h3>{title}</h3></div><p>Informer · clarifier · faire avancer</p></div><div className="bookInfo"><span>{cat}</span><h3>{title}</h3><p>{desc}</p><b>Prochainement</b></div></div>)}</div></section>
<section className="how"><div><span className="serLabel">SIMPLE, DU DÉBUT À LA FIN</span><h2>Choisir. Acheter. Consulter.</h2></div><div className="howSteps"><article><b>01</b><h3>Trouvez votre sujet</h3><p>Parcourez la bibliothèque par situation ou thématique.</p></article><article><b>02</b><h3>Achetez en quelques instants</h3><p>Paiement sécurisé et parcours volontairement court.</p></article><article><b>03</b><h3>Recevez votre guide</h3><p>Le guide est envoyé après l’achat et votre bibliothèque personnelle arrive prochainement.</p></article></div></section>
<section className="closingBanner"><div><span>SER GUIDES</span><h2>S’informer aujourd’hui.<br/>Mieux décider demain.</h2></div><a className="serButton lightButton" href="/guides">Découvrir la bibliothèque →</a></section>
</main>}