import GuideDeck from '../components/GuideDeck';
import {niches} from '../data/guides';
const categories=['Entreprise','Fiscalité','Administratif','Travail','Immobilier','Famille'];
export default function Home(){return <main>
<section className="editorialHero"><div className="heroWords"><span className="serLabel">SER GUIDES · LA BIBLIOTHÈQUE PRATIQUE</span><h1>Des repères clairs.<br/><em>Des décisions plus sereines.</em></h1><p>Des guides numériques conçus comme de vrais compagnons de route : comprendre, vérifier, agir — sans se perdre dans le jargon.</p><div className="heroActions"><a className="serButton" href="/guides/micro-entreprise-2026">Découvrir le Guide 01 <span>→</span></a><a className="quietLink" href="#niches">Explorer les univers</a></div><div className="heroProof"><span>Guides pratiques</span><span>Sources identifiables</span><span>Accès après achat</span></div></div><div className="heroVisual deckHero"><GuideDeck compact/></div></section>
<section className="themeRail"><div><b>Explorer par thème</b>{categories.map(x=><a href="#niches" key={x}>{x}</a>)}</div></section>
<section className="nicheSection" id="niches"><div className="sectionHeading"><div><span className="serLabel">LES UNIVERS SER</span><h2>15 niches. Une même exigence.</h2><p>Chaque niche devient une collection de guides avec sa propre direction visuelle, ses sujets et ses outils.</p></div></div><div className="nicheGrid">{niches.map((n,i)=><article className="nicheCard" key={n.slug}><span>{String(i+1).padStart(2,'0')}</span><h3>{n.fr}</h3><p>{n.descFr}</p><b>{n.slug==='administratif-fiscal'?'Guide 01 disponible':'Guides en préparation'}</b></article>)}</div></section>
<section className="manifesto"><div className="manifestoQuote"><span>LE RÉFLEXE SER</span><h2>Avant d’agir,<br/><em>vérifiez toujours.</em></h2><p>Une information virale ne remplace jamais une source officielle. SER Guides transforme les sujets compliqués en parcours lisibles et actionnables.</p></div><div className="sourceCards"><div><span>01</span><b>Sources officielles</b><p>Les organismes et références utiles sont remis au centre du parcours.</p></div><div><span>02</span><b>Contexte</b><p>Une règle n’a de sens qu’avec sa situation, sa date et ses conditions.</p></div><div><span>03</span><b>Passage à l’action</b><p>Des étapes, checklists et repères pour savoir quoi faire ensuite.</p></div></div></section>
<section className="how"><div><span className="serLabel">SIMPLE, DU DÉBUT À LA FIN</span><h2>Choisir. Acheter. Consulter.</h2></div><div className="howSteps"><article><b>01</b><h3>Trouvez votre sujet</h3><p>Parcourez les 15 univers et leurs guides.</p></article><article><b>02</b><h3>Achetez en quelques instants</h3><p>Paiement sécurisé et parcours volontairement court.</p></article><article><b>03</b><h3>Recevez votre guide</h3><p>Le guide est envoyé après l’achat.</p></article></div></section>
</main>}